/* MARVEL ATLAS V4 — specific post-credit, visual, prop, and soundtrack trails.
   Non-official connections are identified as editorial research observations.
   Official Marvel URLs below support only the adjacent claims that cite them.
   Every relationship has a narrative explanation, not just franchise membership. */
(()=>{'use strict';
const D=window.MARVEL_DATA;if(!D)throw Error('Load data.js first');
const N=new Map(D.nodes.map(n=>[n.id,n]));const aliases=D.aliases||{};
const ids=x=>aliases[x]||x;
const existing=new Set(D.edges.map(e=>[e.a,e.b].sort().join('|')+'|'+e.type+'|'+e.title));
function node(id,type,label,description,spoiler=2){if(N.has(id))return id;const n={id,type,label,universe:'x',description,spoiler,source:'Additional V4 editorial index'};D.nodes.push(n);N.set(id,n);return id}
function edge(a,b,type,title,detail,spoiler=2,source='editorial',url=''){
 a=ids(a);b=ids(b);if(!N.has(a)||!N.has(b))throw Error('Missing V4 bonus endpoint '+a+'/'+b+': '+title);if(a===b)return;
 const sig=[a,b].sort().join('|')+'|'+type+'|'+title;if(existing.has(sig))return;existing.add(sig);
 D.edges.push({a,b,type,title,detail,spoiler,provenance:source==='official'?'confirmed':'editorial',source:source==='official'?'Marvel official':'Curated observation: verify individual scene against source',...(url?{sourceUrl:url}:{})});
}
const MARVEL_GUARDIANS='https://www.marvel.com/articles/movies/guardians-of-the-galaxy-vol-3-soundtrack-favorite-songs';
const MARVEL_MIX='https://www.marvel.com/articles/gear/guardians-of-the-galaxy-vol-3-soundtrack-vinyl-cd';
const MARVEL_BATES='https://www.marvel.com/articles/culture-lifestyle/guardians-of-the-galaxy-composer-tyler-bates-for-scores-podcast/';
const MARVEL_VISION='https://www.marvel.com/articles/tv-shows/marvel-television-visionquest-release-date';
function note(code,kind,label,description,films,{s=2,links=[],source='',provenance='editorial'}={}){
 const id=node('detail-'+code,kind,label,description,s);
 const relation=code.startsWith('credits-')?'postcredit':kind==='music'?'music':kind==='event'?'story':kind==='artifact'?'artifact':'easter-egg';
 for(const f of films)edge(id,f,relation,label,description,s,provenance,source);
 for(const c of links)edge(id,c,kind==='music'?'music':'reference','Related character, prop, or event',description,s,provenance,source);
 // Direct film ↔ film lines make the learning path discoverable without opening the note first.
 for(let i=1;i<films.length;i++)edge(films[i-1],films[i],kind==='music'?'music':kind==='event'?'continuation':relation,label,description,s,provenance,source);
 return id;
}
// End-credit scenes are not simply labelled "same universe"; describe the on-screen setups.
note('credits-ironman-fury','discovery','Post-credit: Nick Fury and the Avengers Initiative','Nick Fury approaches Tony Stark about a wider superhero initiative; The Avengers later assembles the team.',['ironman','avengers'],{s:1});
note('credits-ironman2-hammer','discovery','Post-credit: Mjolnir crater','Coulson reports the discovery of a hammer in New Mexico, setting up Thor’s Earth arrival.',['iron-man-2','thor'],{s:1,links:['mjolnir']});
note('credits-thor-cube','discovery','Post-credit: the Tesseract appears','Fury presents the Tesseract to Erik Selvig; Loki secretly influences the meeting. The object becomes central to The Avengers.',['thor','avengers'],{s:2,links:['tesseract','lokic']});
note('credits-avengers-thanos','discovery','Mid-credit: Thanos learns of Earth','The alien benefactor of Loki’s invasion is revealed, bringing the emerging Infinity Saga into focus.',['avengers','infwar'],{s:2,links:['thanos']});
note('credits-ironman3-bruce','discovery','Post-credit: Tony tells Bruce Banner his story','Tony narrates his anxieties and misadventures to an exhausted Banner; this is a character comedy, not a new timeline.',['iron-man-3','avengers'],{s:1});
note('credits-darkworld-collector','discovery','Mid-credit: Aether entrusted to the Collector','Asgardians deliver the Aether to the Collector because keeping two Infinity Stones near each other seems dangerous.',['thor-the-dark-world','guardians-of-the-galaxy','infwar'],{s:2,links:['stones']});
note('credits-winter-soldier-twins','discovery','Mid-credit: Hydra experiments on the twins','The reveal of Wanda and Pietro in a Hydra facility introduces two characters who become central to Age of Ultron.',['tws','aou'],{s:2,links:['wanda']});
note('credits-aou-gauntlet','discovery','Mid-credit: Thanos takes the gauntlet','Thanos prepares to pursue the Stones personally. The gauntlet depiction is a tease, not a precise step-by-step account of how every Stone is gathered.',['aou','infwar'],{s:2,links:['infinity-gauntlet','thanos']});
note('credits-antman-wasp','discovery','Mid-credit: Hope is shown the Wasp suit','Hank Pym reveals a suit intended for Hope, anticipating her superhero role in Ant-Man and the Wasp.',['ant-man','ant-man-and-the-wasp'],{s:1});
note('credits-antman-civilwar','discovery','Post-credit: Sam and Steve discuss Bucky','The first Ant-Man’s credits scene uses a Civil War-related meeting between Sam, Steve and Bucky; Scott enters their wider conflict.',['ant-man','captain-america-civil-war'],{s:2});
note('credits-strange-thor','discovery','Mid-credit: Doctor Strange offers to help Thor','Strange discusses Odin’s whereabouts with Thor; the interaction reappears in Thor: Ragnarok.',['doctor-strange','thor-ragnarok'],{s:1,links:['strange']});
note('credits-gotg2-adam','discovery','Post-credit: Ayesha plans Adam','A Sovereign leader reveals a new creation called Adam, who later enters the Guardians’ third movie.',['guardians-of-the-galaxy-vol-2','guardians-of-the-galaxy-vol-3'],{s:2});
note('credits-ragnarok-thanos','discovery','Mid-credit: Asgardian ship faces a massive vessel','The Asgardians’ refugee ship encounters Thanos’s warship; Infinity War begins with the immediate consequences.',['thor-ragnarok','infwar'],{s:2});
note('credits-blackpanther-bucky','discovery','Post-credit: Bucky recovers in Wakanda','The Winter Soldier’s recovery in Wakanda helps explain his position among the defenders of the nation in Infinity War.',['black-panther','infwar'],{s:2});
note('credits-antman-quantum','discovery','Mid-credit: Scott trapped in the Quantum Realm','The Snap strands Scott in the Quantum Realm, whose time behavior later enables the Endgame plan.',['ant-man-and-the-wasp','infwar','endgame'],{s:3,links:['quantum-realm']});
note('credits-captainmarvel-pager','discovery','The pager signal reaches Carol','Fury’s emergency pager signal and Carol Danvers’s appearance near the surviving Avengers connect Infinity War, Captain Marvel and Endgame.',['infwar','captain-marvel','endgame'],{s:3});
note('credits-homecoming-vulture','discovery','Post-credit: Vulture protects Peter’s identity','Adrian Toomes does not reveal Peter’s identity to Mac Gargan in prison; this is an unresolved character consequence rather than proof of a future team-up.',['homecoming'],{s:2});
note('credits-farfromhome-skrulls','discovery','Post-credit: Fury and Hill were Skrulls','The apparent Fury and Hill throughout the film were Skrulls acting in their places; Fury’s off-world activity is separately explored in Secret Invasion.',['spider-man-far-from-home','secret-invasion'],{s:3});
note('credits-nwh-venom','discovery','Mid-credit: a symbiote fragment remains','Eddie Brock returns to his own world while leaving a fragment of the Venom symbiote behind in the MCU; its later use was not established at that point.',['venom2','nwh'],{s:3,links:['venomc']});
note('credits-shangchi-beacon','discovery','Mid-credit: the rings emit a signal','Wong, Bruce and Carol investigate an unexplained signal coming from the Ten Rings; its origin is not established by that scene.',['shang-chi-and-the-legend-of-the-ten-rings'],{s:2,links:['ten-rings-weapons','rings-beacon']});
note('credits-eternals-eros','discovery','Mid-credit: Eros meets the Eternals','Eros and Pip arrive to aid the remaining Eternals; the scene establishes a character arrival, not an already-shown Avengers crossover.',['eternals'],{s:3});
note('credits-wakanda-riri','discovery','Riri leaves Wakanda and develops her own story','Riri’s technology and experiences in Wakanda Forever connect to her subsequent solo series Ironheart.',['black-panther-wakanda-forever','ironheart'],{s:1});
note('credits-quantumania-victor','discovery','Post-credit: Victor Timely appears','The Quantumania credits introduce a Kang variant named Victor Timely, who also appears in Loki season two.',['ant-man-and-the-wasp-quantumania','loki'],{s:3});
note('credits-marvels-beast','discovery','Post-credit: Monica enters another mutant-related reality','Monica meets a Beast variant in a different reality; his appearance does not establish that all Fox mutant films occupy one seamless MCU timeline.',['the-marvels','xmen'],{s:3});
note('credits-deadpool-credits','discovery','Credits footage revisits the Fox-Marvel film legacy','Deadpool & Wolverine’s closing montage celebrates previous Fox-era productions and performers, a real-world production tribute rather than proof that those films share one consistent in-universe timeline.',['dpw','xmen','ff05','dp'],{s:2});
note('credits-ff-doomsday','discovery','Fantastic Four and Avengers crossover groundwork','The First Steps era sets up the Fantastic Four’s participation in the Avengers-era story, without disclosing unreleased Doomsday plot details.',['ff','doomsday'],{s:1,source:'https://www.marvel.com/articles/movies/fantastic-four-first-steps-avengers-doomsday-kevin-feige',provenance:'official'});
// Smaller visible scene connections and easter eggs, separated from the film-to-film story spine.
note('egg-cap-shield-ironman2','discovery','Captain America’s shield prototype appears in Iron Man 2','A version of Captain America’s shield appears in Tony Stark’s workshop; this is a visual prop nod, not the complete shield provenance.',['iron-man-2','ca1'],{s:1,links:['captain-shield']});
note('egg-coulson-name','discovery','Agent Coulson links the earliest films','Phil Coulson moves from the Iron Man films to Thor and The Avengers; the familiar agent is a cross-film organizational thread.',['ironman','iron-man-2','thor','avengers'],{s:1});
note('egg-howard-stark','discovery','Howard Stark connects the world war and the Stark legacy','Howard works with Steve during World War II and appears in the Stark family’s later history and the Endgame 1970 detour.',['ca1','ironman','iron-man-2','endgame'],{s:2});
note('egg-infinity-gauntlet-vault','discovery','Odin’s vault gauntlet is not Thanos’s working gauntlet','Thor shows an early gauntlet prop in Odin’s vault. Ragnarok later explicitly calls the vault example fake, distinguishing it from Thanos’s weapon.',['thor','thor-ragnarok','infwar'],{s:2,links:['infinity-gauntlet']});
note('egg-cosmic-morag','discovery','Morag revisited in the Time Heist','The Guardians’ first mission for the Orb is revisited when Endgame’s team travels to a past version of Morag.',['guardians-of-the-galaxy','endgame'],{s:2,links:['stones']});
note('egg-peggy-photo','discovery','Steve and Peggy’s remembered dance','Steve’s missed dance and Peggy’s remembered photo become meaningful across The First Avenger, Winter Soldier and Endgame.',['ca1','tws','endgame'],{s:3});
note('egg-jarvis-cameo','discovery','Edwin Jarvis appears in Endgame','James D’Arcy reprises Edwin Jarvis from Agent Carter when Tony and Steve revisit the 1970 military base; this is a cross-series performance link.',['agentcarter','endgame'],{s:3});
note('egg-hydra-elevator','discovery','Endgame restages the Winter Soldier elevator','Steve meets members of the Hydra strike team during the New York 2012 Time Heist; the scene recalls the earlier elevator fight but replaces the fight with a bluff.',['tws','endgame'],{s:2});
note('egg-red-skull-vormir','discovery','Red Skull reappears as the Stonekeeper','The villain from the First Avenger is encountered as guardian of the Soul Stone in Infinity War and Endgame.',['ca1','infwar','endgame'],{s:3,links:['stones']});
note('egg-mjolnir-jane','discovery','Jane Foster’s Mjolnir story continues beyond the shattered hammer','Ragnarok breaks Mjolnir, the Endgame Time Heist borrows an earlier version, and Love and Thunder gives its reassembled fragments new purpose.',['thor-ragnarok','endgame','thor-love-and-thunder'],{s:2,links:['mjolnir']});
note('egg-mandarin-slat','discovery','Trevor Slattery’s Mandarin persona is revisited','Iron Man 3’s false Mandarin is investigated in All Hail the King, and Trevor later appears during Shang-Chi’s exploration of the real Ten Rings.',['iron-man-3','project-marvel-one-shot-all-hail-the-king','shang-chi-and-the-legend-of-the-ten-rings'],{s:2,links:['ten-rings-organization']});
note('egg-celestial-seed','discovery','The Eternals’ emergence changes Earth','The aborted emergence leaves an enormous Celestial formation in Earth’s ocean; later projects can refer back to this event without requiring all Eternals to meet the Avengers.',['eternals','captain-america-brave-new-world'],{s:2});
note('egg-hulk-abomination','discovery','The Abomination returns after the Hulk film','Emil Blonsky’s earlier conflict with the Hulk matters again in later MCU projects, including She-Hulk, and his cage appearance in Shang-Chi.',['the-incredible-hulk','shang-chi-and-the-legend-of-the-ten-rings','she-hulk-attorney-at-law'],{s:1});
note('egg-kate-yelena','discovery','Kate Bishop and Yelena meet after Vormir','The Hawkeye series revisits Natasha’s death through Yelena’s grief and creates a bond between Kate Bishop and Clint Barton.',['black-widow','endgame','hawkeye'],{s:3});
note('egg-ultron-vision','discovery','Ultron’s creation and Vision’s future are interwoven','Vision’s first appearance follows Ultron’s creation. Marvel’s VisionQuest announcement confirms James Spader returns as Ultron, but the plot remains unreleased.',['aou','wandav','visionquest'],{s:1,source:MARVEL_VISION,provenance:'official'});
note('egg-westview-agatha','discovery','Agatha’s spellcraft moves beyond Westview','Agatha All Along revisits consequences from Westview and Agatha’s interaction with Wanda while expanding the supernatural story.',['wandav','agatha-all-along'],{s:1,links:['westview']});
note('egg-cyclops-professor','discovery','Animated X-Men and live-action films are separate incarnations','The X-Men 1990s animated continuity leads into X-Men ’97. The Fox films are different adaptations despite sharing many character names.',['x-men-97','xmen'],{s:0});
note('egg-human-torch','discovery','The 2005 Human Torch appears in Deadpool and Wolverine','Chris Evans plays a version of Johnny Storm, not Steve Rogers, when he appears in The Void. The 2025 Fantastic Four’s Johnny is a different actor and continuity.',['ff05','dpw','ff'],{s:3,links:['the-void']});
// Music: nodes represent recurring licensed songs, original scores, and writer motifs.
note('music-guardians-redbone','music','“Come and Get Your Love” — Guardians reprise','Redbone’s track accompanies Peter Quill in the original film and returns as an identifiable musical callback in Vol. 3.',['guardians-of-the-galaxy','guardians-of-the-galaxy-vol-3'],{s:1,source:MARVEL_MIX,provenance:'official'});
note('music-guardians-radiohead','music','“Creep” — Guardians Vol. 3 opening','Radiohead’s acoustic Creep opens the third Guardians film and frames Rocket and the team’s mood.',['guardians-of-the-galaxy-vol-3'],{s:1,source:MARVEL_GUARDIANS,provenance:'official'});
note('music-guardians-beastie','music','“No Sleep Till Brooklyn” — corridor sequence','The Beastie Boys song accompanies the memorable combat sequence near the climax of Guardians Vol. 3.',['guardians-of-the-galaxy-vol-3'],{s:2,source:MARVEL_GUARDIANS,provenance:'official'});
note('music-guardians-florence','music','“Dog Days Are Over” — farewell sequence','Florence + The Machine accompanies the team’s emotional dancing and transition in Vol. 3.',['guardians-of-the-galaxy-vol-3'],{s:3,source:MARVEL_GUARDIANS,provenance:'official'});
note('music-guardians-bates','music','Tyler Bates’s Guardians orchestral score','Composer Tyler Bates provided instrumental scoring across the first two Guardians films; it operates alongside their curated pop soundtracks.',['guardians-of-the-galaxy','guardians-of-the-galaxy-vol-2'],{s:0,source:MARVEL_BATES,provenance:'official'});
note('music-awesome-mix','music','The Awesome Mix tapes and Star-Lord’s music','Peter’s mother’s tapes make his favorite music part of his character history across the Guardians films.',['guardians-of-the-galaxy','guardians-of-the-galaxy-vol-2','guardians-of-the-galaxy-vol-3'],{s:1,source:MARVEL_GUARDIANS,provenance:'official'});
note('music-avengers-motif','music','The Avengers orchestral identity','The recurring Avengers theme links the team’s original formation to its later major gatherings. The exact arrangement differs between films.',['avengers','aou','infwar','endgame'],{s:1});
note('music-cap-theme','music','Steve Rogers’s musical identity','The Captain America hero theme and later arrangements provide musical continuity for his larger MCU arc.',['ca1','endgame'],{s:1});
note('music-wandav-sitcom','music','WandaVision’s sitcom-era theme pastiches','Different faux-sitcom opening themes reveal WandaVision’s deliberate movement through TV eras; they are original show songs, not quotations from historic sitcom scripts.',['wandav'],{s:1});
note('music-agatha-ballad','music','The Ballad of the Witches’ Road','The coven’s song is integral to the plot and is introduced in Agatha All Along; variations gain different meanings as the story unfolds.',['agatha-all-along'],{s:1,links:['witches-ballad']});
note('music-loki-theme','music','Loki theme across seasons','Natalie Holt’s musical language links Loki’s identity, the TVA and the two seasons of the series.',['loki'],{s:1,links:['time-variance-authority']});
note('music-blackpanther-scores','music','Wakanda’s musical world','The two Black Panther films use a sustained Wakandan sonic identity, with different musical choices reflecting changes in the story.',['black-panther','black-panther-wakanda-forever'],{s:1});
note('music-spider-man-original-cartoon','music','The classic Spider-Man theme and adaptations','Spider-Man screen adaptations can reference the familiar animated-series theme in different ways; these are musical references, not evidence of a shared fictional timeline.',['sm1','homecoming','itsv'],{s:1});
D.v4=D.v4||{};D.v4.bonusLayer=true;
})();
